.gt-install:
  script: &gt-install-script
    - ./lib/gt/src/gitlab/install-gt.sh

.gt-create-mr:
  script: &gt-create-mr-script
    - source ./lib/gt/src/gitlab/create-mr.sh

.gt-update:
  stage: gt
  image: tegonal/gitlab-git:latest
  rules:
    - if: $DO_GT_UPDATE
  variables:
    GITBOT_USERNAME: 'gt bot'
    GITBOT_EMAIL: 'gt@tegonal.com'
  before_script:
    - apk update && apk add bash git gnupg perl coreutils curl && apk upgrade
    - tmpDir=$(mktemp -d -t gt-update-XXXXXXXXXX) && cd "$tmpDir"
    - source /scripts/clone-current.sh
    - export PATH="$PATH:$HOME/.local/bin"
  script:
    - *gt-install-script
    - gt reset --gpg-only true
    - gt update
    - *gt-create-mr-script

gt-update:
  extends: .gt-update

.gt-update-stop-pipeline:
  stage: gt
  image: alpine:latest
  rules:
    - if: $DO_GT_UPDATE
  needs: [ "gt-update" ]
  script:
    - apk update && apk add curl
    - echo 'stopping the pipeline on purpose...'
    - 'curl --request POST --header "PRIVATE-TOKEN: $GT_UPDATE_API_TOKEN" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/jobs/${CI_JOB_ID}/cancel"'
    - sleep
    - echo 'cancel failed, stopping via exit...'
    - exit 1
gt-update-stop-pipeline:
  extends: .gt-update-stop-pipeline
