name: "Code Quality"
on: [push, pull_request]

jobs:
  CodeQuality:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@1.1.0
        with:
          ignore: lib/tegonal-scripts
        env:
          SHELLCHECK_OPTS: -s bash -S info -x -o all -e SC2312 -P ./src

      - name: check all scripts have documentation
        run: ./scripts/update-docu.sh
