name: "Installation"
on:
  push:
    branches:
      - main

jobs:
  install:
    name: "Install latest"
    runs-on: ubuntu-latest
    steps:
      - name: Import gpg key(s) defined in secrets.PUBLIC_GPG_KEYS_WE_TRUST
        run: gpg --import - <<< "${{ secrets.PUBLIC_GPG_KEYS_WE_TRUST }}"
      - uses: actions/checkout@v3
      - name: Check it works
        run: |
          tmpDir=$(mktemp -d -t gget-download-install-XXXXXXXXXX)
          mkdir -p "$tmpDir"
          currentDir=$(pwd)
          cd "$tmpDir"
          "$currentDir/install.sh"
      - name: run self-update
        run: gget self-update

  installDoc:
    name: "Install.doc.sh latest"
    runs-on: ubuntu-latest
    steps:
      - name: Import gpg key(s) defined in secrets.PUBLIC_GPG_KEYS_WE_TRUST
        run: gpg --import - <<< "${{ secrets.PUBLIC_GPG_KEYS_WE_TRUST }}"
      - uses: actions/checkout@v3
      - name: Check it works
        run: ./install.doc.sh
      - name: run self-update
        run: gget self-update

  installOld:
    name: "Install old version, self-update to latest"
    strategy:
      matrix:
        tag: [v0.5.2, v0.5.0, v0.4.1]
    runs-on: ubuntu-latest
    steps:
      - name: Import gpg key(s) defined in secrets.PUBLIC_GPG_KEYS_WE_TRUST
        run: gpg --import - <<< "${{ secrets.PUBLIC_GPG_KEYS_WE_TRUST }}"
      - uses: actions/checkout@v3
      - name: install ${{ matrix.tag }}
        run: |
          tmpDir=$(mktemp -d -t gget-download-install-XXXXXXXXXX)
          mkdir -p "$tmpDir"
          currentDir=$(pwd)
          cd "$tmpDir"
          "$currentDir/install.sh" -t ${{ matrix.tag }}
      - name: run self-update
        run: gget self-update
